Task 3

Team:

Create a team notebook to read in the COVID-19 data (cases, deaths, and population) 
using pandas and display the dataframe in a notebook.

In [1]:
import os
import pandas as pd

df1 = pd.read_csv("covid_confirmed_usafacts.csv")
df2 = pd.read_csv("covid_deaths_usafacts.csv")
df3 = pd.read_csv("covid_county_population_usafacts.csv")

In [2]:
#covid_confirmed_usafacts.csv

df1

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2023-07-14,2023-07-15,2023-07-16,2023-07-17,2023-07-18,2023-07-19,2023-07-20,2023-07-21,2023-07-22,2023-07-23
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,19913,19913,19913,19913,19913,19913,19913,19913,19913,19913
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,70521,70521,70521,70521,70521,70521,70521,70521,70521,70521
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,7582,7582,7582,7582,7582,7582,7582,7582,7582,7582
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,8149,8149,8149,8149,8149,8149,8149,8149,8149,8149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,12645,12645,12645,12645,12645,12645,12645,12645,12645,12645
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,12206,12206,12206,12206,12206,12206,12206,12206,12206,12206
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,6468,6468,6468,6468,6468,6468,6468,6468,6468,6468
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,2640,2640,2640,2640,2640,2640,2640,2640,2640,2640
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,1914,1914,1914,1914,1914,1914,1914,1914,1914,1914

In [3]:
#covid_deaths_usafacts.csv

df2

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2023-07-14,2023-07-15,2023-07-16,2023-07-17,2023-07-18,2023-07-19,2023-07-20,2023-07-21,2023-07-22,2023-07-23
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,235,235,235,235,235,235,235,235,235,235
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,731,731,731,731,731,731,731,731,731,731
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,104,104,104,104,104,104,104,104,104,104
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,111,111,111,111,111,111,111,111,111,111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,142,142,142,142,142,142,142,142,142,142
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,16,16
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,43,43
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,51,51,51,51,51,51,51,51,51,51
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,24,24,24,24,24,24,24,24,24,24

In [4]:
#covid_county_population_usafacts.csv

df3

      countyFIPS            County Name State  population
0              0  Statewide Unallocated    AL           0
1           1001         Autauga County    AL       55869
2           1003         Baldwin County    AL      223234
3           1005         Barbour County    AL       24686
4           1007            Bibb County    AL       22394
...          ...                    ...   ...         ...
3188       56037      Sweetwater County    WY       42343
3189       56039           Teton County    WY       23464
3190       56041           Uinta County    WY       20226
3191       56043        Washakie County    WY        7805
3192       56045          Weston County    WY        6927

[3193 rows x 4 columns]

Task3

team:

Merge all the three variables (cases, deaths, and population) to create a super COVID-19 datafame. Export it to a csv format.

In [5]:
#SuperCovid19


temp=pd.merge(df1,df2,left_index=True, right_index=True, how='inner')
temper=pd.merge(temp,df3,left_index=True, right_index=True, how='inner')
temper.to_csv("super_covid.csv")

del temper['countyFIPS_y']
del temper['County Name_y']
del temper['State_y']
del temper['StateFIPS_y']
del temper['countyFIPS']
del temper['County Name']

temper.to_csv("S_covid.csv")
temper

,countyFIPS_x,County Name_x,State_x,StateFIPS_x,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2023-07-16_y,2023-07-17_y,2023-07-18_y,2023-07-19_y,2023-07-20_y,2023-07-21_y,2023-07-22_y,2023-07-23_y,State,population
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,AL,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,235,235,235,235,235,235,235,235,AL,55869
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,731,731,731,731,731,731,731,731,AL,223234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,104,104,104,104,104,104,104,104,AL,24686
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,111,111,111,111,111,111,111,111,AL,22394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,142,142,142,142,142,142,142,142,WY,42343
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,WY,23464
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,WY,20226
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,51,51,51,51,51,51,51,51,WY,7805
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,24,24,24,24,24,24,24,24,WY,6927